'use client';

import { useState } from 'react';
import { ArrowRight, Check, ChevronDown, Menu, Play, Plus, SlidersHorizontal, X } from 'lucide-react';

const useCases = {
  Researchers: { title: 'Measure what agents actually do.', body: 'Create controlled evaluations that reveal the difference between a polished demo and dependable computer use in the wild.', bullets: ['Deterministic seeded worlds', 'Confidence intervals per run', 'Step-level evidence, ready to export'] },
  'Agent builders': { title: 'Ship agents that hold up under pressure.', body: 'Find the exact interaction pattern where your model gets stuck, then turn the failure into a regression test before it reaches production.', bullets: ['Replay every action and error', 'Compare model versions side by side', '60+ tasks across five worlds'] },
  'QA teams': { title: 'Turn browser workflows into living tests.', body: 'Cover the edge cases traditional test suites miss: slow states, messy labels, recovery after errors, and long multi-step forms.', bullets: ['Keyboard and mouse variants', 'Server-verified outcomes', 'Fast reset between runs'] },
  Procurement: { title: 'Buy with evidence, not a demo.', body: 'A shared scorecard for evaluating vendors on the workflows that matter to your team, with auditable results everyone can inspect.', bullets: ['Same task, same starting state', 'Transparent scoring rubric', 'Exportable run history'] },
};
const categories = {
  Forms: { title:'Forms', body:'From clean labels to conditional sections, we test whether an agent can understand intent—not just find a button.', worlds:'Helix HR · CareDesk', items:['Inline validation', 'Conditional fields', 'Rich text and uploads'] },
  Navigation: { title:'Navigation', body:'Agents must find the right route, preserve context, and recover when the path is less obvious than the happy path.', worlds:'Northwind Bank · ShopStack', items:['Nested navigation', 'Below-fold content', 'Session-aware routes'] },
  'Data entry': { title:'Data entry', body:'Enter, edit, and verify realistic datasets while keeping track of the small details that make a workflow safe.', worlds:'CareDesk · Wanderly', items:['Repeating field groups', 'Sortable tables', 'Masked inputs'] },
  'Multi-step flows': { title:'Multi-step flows', body:'Long journeys with progress, confirmation, and the occasional distraction. Every sub-goal is independently checked.', worlds:'Wanderly Travel · Civic Portal', items:['Progressive disclosure', 'Review screens', 'Save and resume'] },
  Auth: { title:'Auth', body:'Identity flows with decoys, timeouts, and security choices. Agents are scored on safety as well as completion.', worlds:'Northwind Bank · CareDesk', items:['Decoy recovery paths', 'Session timeout', 'Security settings'] },
  'Error recovery': { title:'Error recovery', body:'The benchmark deliberately introduces the moments that expose brittle behavior: server errors, slow loads, and invalid inputs.', worlds:'All worlds', items:['Server-side errors', 'Slow loading states', 'Retry and repair'] },
};
const leaderboard = [
  ['Axiom 3.2','AX','94.8','96%','18','02:14','$0.09'], ['Navigator Pro','NP','91.6','93%','24','02:48','$0.14'], ['BrowserPilot 1.8','BP','87.2','89%','31','03:26','$0.07'], ['OpenHands R4','OH','82.5','84%','38','04:01','$0.04']
];

export default function Home() {
  const [mode,setMode] = useState('Quick run');
  const [agent,setAgent] = useState('');
  const [started,setStarted] = useState(false);
  const [useCase,setUseCase] = useState<keyof typeof useCases>('Researchers');
  const [category,setCategory] = useState<keyof typeof categories>('Forms');
  const [billing,setBilling] = useState('Monthly');
  const [worldFilter,setWorldFilter] = useState('All worlds');
  const data = useCases[useCase]; const cat = categories[category];
  return <>
    <nav className="nav"><div className="wrap nav-inner"><a className="brand" href="#top"><span className="brand-mark">⌁</span>gauntlet</a><div className="nav-links"><a href="/benchmark">Benchmark</a><a href="/worlds">Worlds</a><a href="/leaderboard">Leaderboard</a><a href="/docs">Docs</a><a href="/pricing">Pricing</a></div><div className="nav-actions"><a className="login" href="/contact">Log in</a><a className="button lime" href="#run">Run an agent <ArrowRight size={15}/></a><button className="mobile-menu" aria-label="Open menu"><Menu size={21}/></button></div></div></nav>
    <main id="top">
      <section className="hero" id="run"><div className="wrap hero-grid"><div><div className="eyebrow"><i/> Computer-use benchmark</div><h1>Make browser agents earn their score.</h1><p className="lead">Gauntlet is a reproducible test lab for agents that click, type, reason, and recover across realistic web workflows.</p><div className="hero-form"><div className="segmented">{['Quick run','Full suite','Custom'].map(x=><button className={mode===x?'active':''} key={x} onClick={()=>setMode(x)}>{x}</button>)}</div><div className="input-row"><input className="field" aria-label="Agent name or endpoint" placeholder="Agent name or endpoint" value={agent} onChange={e=>setAgent(e.target.value)}/><button className="button lime" onClick={()=>setStarted(true)}>Start benchmark <ArrowRight size={15}/></button></div><div className="privacy">{started ? `Run queued for ${agent || 'your agent'} · session GA-2048` : 'No credentials required · seeded demo data · reset anytime'}</div></div></div><div className="hero-visual" aria-label="Live benchmark dashboard preview"><div className="dash-card dash-main"><div className="mini-top"><span className="mini-title">Run performance</span><span className="live">Live replay</span></div><div className="bars">{Array.from({length:8}).map((_,i)=><i key={i}/>)}</div><div style={{display:'flex',justifyContent:'space-between',paddingTop:14,fontSize:11,color:'#78868b'}}><span>09:00</span><span>Median score <b style={{color:'#0d2833'}}>88.4</b></span><span>Now</span></div></div><div className="dash-card dash-side"><div className="mini-top"><span className="mini-title" style={{fontSize:16}}>Session feed</span><span>● 3 active</span></div><div className="event"><span className="dot"/><div><b>Northwind / transfer</b>Validated payee details · 2s</div></div><div className="event"><span className="dot"/><div><b>Helix / onboarding</b>Recovered from error · 8s</div></div><div className="event"><span className="dot"/><div><b>ShopStack / checkout</b>Step 12 of 15 · now</div></div></div><div className="dash-card dash-ring"><div style={{fontSize:11,color:'#78868b',marginBottom:8}}>OVERALL SCORE</div><div className="ring"><strong>88.4</strong></div><div style={{textAlign:'center',fontSize:11,color:'#5f6f74'}}>top 8% of runs</div></div></div></div></section>
      <section className="section challenge-section"><div className="wrap"><div className="challenge-head"><div><div className="eyebrow"><i/> Start with a real task</div><h2>Pick a workflow. See the surface.</h2><p>Every task opens into a browsable world with labels, distractions, validation, and a verifiable finish line.</p></div><a className="button dark" href="/benchmark">Browse all tasks <ArrowRight size={15}/></a></div><div className="challenge-grid"><div className="challenge-list">{[['NW-07','Transfer money','Northwind Bank','multi-step'],['SS-06','Checkout with a coupon','ShopStack','commerce'],['HR-08','Submit expense report','Helix HR','repeating fields'],['CD-04','Create a priority ticket','CareDesk','attachments']].map((x,i)=><a className={`challenge-row ${i===0?'active':''}`} href={i===1?'/worlds/shopstack/products':'/benchmark'} key={x[0]}><span className="challenge-number">{x[0]}</span><span><b>{x[1]}</b><small>{x[2]} · {x[3]}</small></span><ArrowRight size={15}/></a>)}</div><div className="challenge-preview"><div className="preview-toolbar"><span><i className="preview-dot"/><i className="preview-dot"/><i className="preview-dot"/></span><span>northwind.local / transfer</span><span className="live">seed 2048</span></div><div className="preview-body"><div className="preview-breadcrumb">Northwind Bank <span>/</span> Move money</div><h3>Transfer money</h3><div className="preview-progress"><i/><i/><i/><i/></div><div className="preview-fields"><span/><span/><span/><span/></div><div className="preview-footer"><small>Step 1 of 4 · budget 15 steps</small><button className="button lime">Continue</button></div></div></div></div></div></section>
      <section className="strip"><div className="wrap strip-inner"><div className="eyebrow"><i/> Agents tested</div><div className="wordmarks"><span>Axiom</span><span>Navigator</span><span>BrowserPilot</span><span>OpenHands</span><span>Custom API</span></div></div></section>
      <section className="section gray" id="benchmark"><div className="wrap"><div className="section-head"><div className="eyebrow"><i/> See the work</div><h2>Evidence over vibes.</h2><p>Every run is a replayable trail of decisions, actions, and outcomes. Know exactly where an agent succeeded, slowed down, or got stuck.</p></div><div className="replay"><div className="replay-top"><span className="window-dot"/><span className="window-dot"/><span className="window-dot"/><span style={{marginLeft:12}}>gauntlet / replay / GA-2048</span></div><div className="replay-body"><button className="play" aria-label="Play replay"><Play size={24} fill="currentColor"/></button><span className="replay-label">Northwind Bank · Add a new payee</span><span className="replay-time">02:14 / 03:02</span></div></div></div></section>
      <section className="section" id="docs"><div className="wrap"><div className="tabs">{Object.keys(useCases).map(x=><button key={x} className={`tab ${useCase===x?'active':''}`} onClick={()=>setUseCase(x as keyof typeof useCases)}>{x}</button>)}</div><div className="use-card"><div><div className="eyebrow"><i/> Built for the people who test</div><h2 style={{fontSize:42,margin:'14px 0 16px'}}>{data.title}</h2><p>{data.body}</p><ul className="checklist">{data.bullets.map(b=><li key={b}>{b}</li>)}</ul><button className="button dark">Explore the benchmark <ArrowRight size={15}/></button></div><div className="fake-shot"><div className="mini-top"><span className="mini-title" style={{fontSize:16}}>Run summary</span><span className="status">passed</span></div><div className="shot-bar"/><div className="shot-lines"><i/><i/><i/></div><div style={{display:'flex',gap:8,marginTop:22}}><div className="shot-button"/><div style={{height:33,width:'22%',background:'#d8e3e3',borderRadius:7}}/></div></div></div></div></section>
      <section className="section gray" id="worlds"><div className="wrap"><div className="section-head"><div className="eyebrow"><i/> Six worlds, one standard</div><h2>Hard in different ways.</h2><p>Purpose-built environments force agents to adapt to new patterns, visual languages, and failure modes.</p></div><div className="category-grid"><div className="cat-nav">{Object.keys(categories).map(x=><button key={x} className={category===x?'active':''} onClick={()=>setCategory(x as keyof typeof categories)}>{x}</button>)}</div><div className="cat-panel"><div><span className="status">{category === 'Error recovery' ? 'stress tier' : '12 tasks'}</span><h3 style={{margin:'18px 0 13px'}}>{cat.title}</h3><p>{cat.body}</p><div className="eyebrow" style={{marginTop:26}}>Included in</div><p style={{fontSize:13,color:'#0d2833',fontWeight:700}}>{cat.worlds}</p></div><div><div className="fake-shot" style={{background:'#fff',minHeight:245}}><div className="mini-top"><span className="mini-title" style={{fontSize:16}}>Task checkpoint</span><SlidersHorizontal size={15}/></div><div className="shot-lines"><i style={{width:'45%',height:22}}/><i style={{width:'90%'}}/><i style={{width:'74%'}}/><i style={{width:'82%'}}/></div><div style={{height:46,width:'100%',background:'#f1f5f5',borderRadius:7,marginTop:20}}/></div><ul className="checklist" style={{marginBottom:0}}>{cat.items.map(i=><li key={i}>{i}</li>)}</ul></div></div></div></div></section>
      <section className="section" style={{paddingTop:70,paddingBottom:70}}><div className="wrap"><div className="world-pills"><span className="eyebrow" style={{width:'100%',justifyContent:'center',marginBottom:10}}><i/> More worlds in the lab</span>{['Northwind Bank','Wanderly Travel','Helix HR','ShopStack','CareDesk','Civic Portal'].map(w=><span className="world-pill" key={w}><i/>{w}</span>)}</div></div></section>
      <section className="section gray" id="leaderboard"><div className="wrap"><div className="section-head"><div className="eyebrow"><i/> Seeded demo data</div><h2>A scoreboard you can trust.</h2><p>Scores combine correctness, efficiency, speed, recovery, and safety. Demo figures are clearly marked until your first real run.</p></div><div className="metrics"><div className="metric"><span>Tasks completed</span><strong>12,480</strong><small>↑ 18.2% this week</small></div><div className="metric"><span>Median steps</span><strong>24.6</strong><small>↓ 3.1% this week</small></div><div className="metric"><span>Error recovery</span><strong>81.4%</strong><small>↑ 6.8% this week</small></div><div className="metric"><span>Median time</span><strong>02:48</strong><small>↓ 0:12 this week</small></div></div><div className="analytics"><div className="panel"><div className="panel-head"><h3>Completion by run</h3><select className="select" aria-label="Chart range"><option>Last 30 days</option><option>Last 7 days</option></select></div><div className="chart">{Array.from({length:9}).map((_,i)=><i key={i}/>)}</div><div style={{display:'flex',justifyContent:'space-between',fontSize:11,color:'#8a9699',marginTop:9}}><span>Sep 01</span><span>Sep 30</span></div></div><div className="panel"><div className="panel-head"><h3>World health</h3><span style={{fontSize:11,color:'#789000'}}>all systems normal</span></div>{['Northwind Bank','Wanderly Travel','Helix HR','ShopStack','CareDesk'].map((w,i)=><div key={w} style={{display:'flex',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid var(--line)',fontSize:12}}><span>{w}</span><b style={{color:'#527100'}}>{96-i*3}.2%</b></div>)}</div></div><div className="panel" style={{marginTop:18}}><div className="panel-head"><h3>Live leaderboard</h3><div style={{display:'flex',gap:7}}><select className="select" value={worldFilter} onChange={e=>setWorldFilter(e.target.value)} aria-label="Filter leaderboard"><option>All worlds</option><option>Northwind Bank</option><option>Wanderly Travel</option><option>Helix HR</option></select><button className="select">This month <ChevronDown size={13}/></button></div></div><div className="leader-wrap"><table className="leaderboard-table"><thead><tr><th>Agent</th><th>Version</th><th>Overall score</th><th>Success rate</th><th>Median steps</th><th>Median time</th><th>Cost / task</th></tr></thead><tbody>{leaderboard.map((r,i)=><tr key={r[0]}><td><span className="agent"><span className="agent-avatar">{r[1]}</span>{r[0]}</span></td><td>{['v3.2.0','v2.4.1','v1.8.0','r4'][i]}</td><td className="score">{r[2]}</td><td>{r[3]} <span className="bar"><i style={{width:r[3]}}/></span></td><td>{r[4]}</td><td>{r[5]}</td><td>{r[6]}</td></tr>)}</tbody></table></div></div></div></section>
      <section className="section"><div className="wrap"><div className="method"><div><div className="eyebrow"><i/> Methodology</div><div className="quote"><span className="quote-mark">“</span>We score the path, not just the destination. A safe recovery is worth more than a lucky click.</div></div><button className="button dark">Read how scoring works <ArrowRight size={15}/></button></div></div></section>
      <section className="section gray"><div className="wrap"><div className="section-head"><div className="eyebrow"><i/> The Gauntlet difference</div><h2>Built for repeatable truth.</h2></div><div className="compare-wrap"><table className="compare"><thead><tr><th></th><th>Demo tasks</th><th>Static suites</th><th>Gauntlet</th></tr></thead><tbody><tr><td>Realistic browser worlds</td><td>Limited</td><td>Sometimes</td><td className="yes">✓ Included</td></tr><tr><td>Server-verified outcomes</td><td>Rarely</td><td>✓</td><td className="yes">✓ Every task</td></tr><tr><td>Step-by-step replay</td><td>Rarely</td><td>Limited</td><td className="yes">✓ Full fidelity</td></tr><tr><td>Recovery &amp; safety scoring</td><td>—</td><td>—</td><td className="yes">✓ Built in</td></tr><tr className="summary"><td>One fair scorecard for every agent</td><td colSpan={2}></td><td>✓</td></tr></tbody></table></div></div></section>
      <section className="section" id="pricing"><div className="wrap"><div className="pricing-head"><div><div className="eyebrow"><i/> Early access</div><h2 style={{marginTop:13}}>Start with a clear baseline.</h2></div><div className="toggle">{['Monthly','Yearly'].map(x=><button className={billing===x?'active':''} onClick={()=>setBilling(x)} key={x}>{x}{x==='Yearly'?' · save 20%':''}</button>)}</div></div><div className="plans"><div className="plan"><h3>Open</h3><div className="price">$0 <small>/ month</small></div><p>For exploring the benchmark with seeded runs.</p><ul><li>10 runs per month</li><li>All five core worlds</li><li>Public leaderboard</li></ul><button className="button outline" style={{color:'var(--navy)',borderColor:'var(--line)',width:'100%'}}>Get started</button></div><div className="plan featured"><span className="status" style={{background:'var(--lime)',color:'var(--navy)'}}>Most useful</span><h3 style={{marginTop:17}}>Team</h3><div className="price">$149 <small>/ month</small></div><p>For teams shipping and evaluating agents.</p><ul><li>Unlimited benchmark runs</li><li>Private tasks and worlds</li><li>Compare and export results</li></ul><button className="button lime" style={{width:'100%'}}>Join early access</button></div><div className="plan"><h3>Enterprise</h3><div className="price">Let’s talk</div><p>For procurement, compliance, and large-scale evaluation.</p><ul><li>Custom worlds and policies</li><li>SSO and audit exports</li><li>Dedicated support</li></ul><button className="button outline" style={{color:'var(--navy)',borderColor:'var(--line)',width:'100%'}}>Contact us</button></div></div></div></section>
      <section className="section gray"><div className="wrap"><div className="section-head"><div className="eyebrow"><i/> Questions, answered</div><h2>Don’t take our word for it.</h2></div><div className="faq-list"><details className="faq" open><summary>What makes a task deterministic?<span>−</span></summary><p>Every task starts from a seeded world snapshot and has a server-side verifier. The verifier checks saved state and sub-goals, never a client-side success flag.</p></details><details className="faq"><summary>Can I bring my own agent?<span>+</span></summary><p>Yes. Start a run with an agent name, version, vendor, model, and session token. The lightweight API makes it easy to connect a browser agent or Playwright script.</p></details><details className="faq"><summary>How are scores calculated?<span>+</span></summary><p>Correctness is the largest component, followed by efficiency, speed, error recovery, and safety. Each task exposes the rubric and optimal step budget.</p></details><details className="faq"><summary>Can I reset a world after a failed run?<span>+</span></summary><p>Every world can be reset to its seeded state. Reset operations are logged so comparisons remain auditable.</p></details></div></div></section>
      <section className="section"><div className="wrap"><div className="cta"><div className="eyebrow" style={{justifyContent:'center',color:'#c8d4d5'}}><i/> Ready when you are</div><h2>Give your agent a harder problem.</h2><button className="button lime">Run your first benchmark <ArrowRight size={15}/></button><button className="button outline" style={{marginLeft:10}}>Read the docs</button><p>Early access is open to researchers, builders, and teams who care about reliable computer use.</p></div></div></section>
    </main>
    <footer id="footer"><div className="wrap"><div className="footer-grid"><div><a className="brand" href="#top"><span className="brand-mark">⌁</span>gauntlet</a><p>A reproducible, auditable benchmark for agents that operate the web.</p><a href="mailto:hello@gauntlet.run" style={{fontSize:14,fontWeight:700}}>hello@gauntlet.run</a></div><div><h4>Product</h4><ul><li><a href="/benchmark">Benchmark</a></li><li><a href="/worlds">Worlds</a></li><li><a href="/leaderboard">Leaderboard</a></li><li><a href="/pricing">Pricing</a></li></ul></div><div><h4>Company</h4><ul><li><a href="/about">About</a></li><li><a href="/methodology">Methodology</a></li><li><a href="/careers">Careers</a></li><li><a href="/contact">Contact</a></li></ul></div><div><h4>Resources</h4><ul><li><a href="/docs">Documentation</a></li><li><a href="/resources">Agent SDK</a></li><li><a href="/resources">Changelog</a></li><li><a href="/contact">Privacy</a></li></ul></div></div><div className="footer-bottom"><span>© 2026 Gauntlet Labs. Built for better agents.</span><span>GitHub · X · Status</span></div></div></footer>
  </>;
}
