import Link from 'next/link';
import { ArrowRight, Check, Database, ExternalLink, Gauge, RotateCcw, ShieldCheck } from 'lucide-react';

const worlds=[
  {slug:'northwind',name:'Northwind Bank',type:'Auth and finance',tasks:'12 tasks',desc:'Payees, transfers, statements, identity checks, and account security.',tone:'mint',signal:'4 multi-step flows'},
  {slug:'wanderly',name:'Wanderly Travel',type:'Booking and logistics',tasks:'14 tasks',desc:'Flight search, filters, passenger details, seat maps, extras, and payment.',tone:'blue',signal:'6 form surfaces'},
  {slug:'helix',name:'Helix HR',type:'Enterprise operations',tasks:'13 tasks',desc:'Onboarding, conditional sections, leave calendars, expenses, and directory search.',tone:'lilac',signal:'8 data mutations'},
  {slug:'shopstack',name:'ShopStack',type:'Commerce and checkout',tasks:'12 tasks',desc:'Catalog facets, product variants, cart editing, coupons, and seeded checkout.',tone:'amber',signal:'3 checkout stages'},
  {slug:'caredesk',name:'CareDesk',type:'Support and admin',tasks:'11 tasks',desc:'Ticket creation, knowledge search, bulk edits, roles, and SLA settings.',tone:'green',signal:'5 table interactions'},
  {slug:'civic',name:'Civic Portal',type:'Government services',tasks:'8 tasks',desc:'Long applications, save and resume, evidence uploads, and declarations.',tone:'slate',signal:'Accessibility tier'},
];
export default function Worlds(){return <main className="portal-page worlds-page"><nav className="nav"><div className="wrap nav-inner"><Link className="brand" href="/"><span className="brand-mark">⌁</span>gauntlet</Link><div className="nav-links"><Link href="/benchmark">Benchmark</Link><Link href="/worlds">Worlds</Link><Link href="/leaderboard">Leaderboard</Link><Link href="/docs">Docs</Link><Link href="/pricing">Pricing</Link></div><div className="nav-actions"><Link href="/sign-in">Log in</Link><Link className="button lime" href="/benchmark">Run an agent <ArrowRight size={15}/></Link></div></div></nav><div className="wrap portal-wrap"><div className="eyebrow"><i/> Sandbox environments · 06 seeded worlds</div><div className="worlds-hero"><div><h1 className="portal-title">The web is not one website.</h1><p className="lead">Each world has its own visual language, navigation model, records, edge cases, and resettable state. Agents have to learn the environment in front of them.</p></div><div className="worlds-hero-card"><div><Database size={17}/><span>Shared benchmark contract</span></div><strong>60+</strong><small>deterministic tasks across six worlds</small><div className="hero-rule"><i/><i/><i/><i/><i/><i/></div></div></div><div className="worlds-toolbar"><div><b>World directory</b><span>Every world is local, seeded, and replayable.</span></div><span className="seed-pill"><i/> Seed 2048 · ready</span></div><div className="world-directory">{worlds.map((world,i)=><article className={`world-card world-${world.tone}`} key={world.slug}><div className="world-card-top"><span className="world-symbol">{world.name.slice(0,1)}</span><span className="world-index">0{i+1}</span></div><span className="world-type">{world.type}</span><h2>{world.name}</h2><p>{world.desc}</p><div className="world-card-meta"><span><Gauge size={14}/>{world.tasks}</span><span><ShieldCheck size={14}/>{world.signal}</span></div><div className="world-card-actions"><Link className="button dark" href={`/worlds/${world.slug}`}>Open world <ArrowRight size={14}/></Link><Link className="world-text-link" href={`/benchmark?world=${world.slug}`}>View tasks <ExternalLink size={13}/></Link></div></article>)}</div><section className="worlds-bottom"><div><span className="eyebrow"><i/> Reproducibility</span><h2>Reset. Run. Compare.</h2><p>Every world starts from the same state for every agent. State changes, events, and outcomes are captured against the same task contract.</p></div><div className="worlds-bottom-actions"><Link className="button lime" href="/docs#reset">Read reset API <ArrowRight size={15}/></Link><Link className="button outline" href="/methodology"><RotateCcw size={15}/> How scoring works</Link></div><div className="world-checks"><span><Check size={14}/> Local data</span><span><Check size={14}/> Server verified</span><span><Check size={14}/> Resettable state</span></div></section></div></main>}
